### ISSUE TITLE
Building of Jamulus fails due to DBUS error

### ISSUE THREAD

**Issue by ann0see** [flathub/io.jamulus.Jamulus#175]
The build seems to fail due to the following error: finish-args-arbitrary-dbus-access.

Does anyone know how to fix that? Upstream (we) had an update request, but as there seems to be a build related issue, this can't be updated easily.

@ranfdev @joao-p-marques do you have any insight?

**Comment by ann0see** [comment]
See the log here: https://buildbot.flathub.org/#/builders/6/builds/8699

**Comment by joao-p-marques** [comment]
Hi @ann0see 
Thanks for the help in updating the icon, I've been wanting to do that for a while, but haven't had time yet... 
About the error you point out, I have no idea what it is about... Maybe @ranfdev or @hoffie know something. Can you help?

**Comment by ranfdev** [comment]
The line causing the issue is in the flatpak manifest:
`  - --socket=system-bus`

Access to the entire system-bus is probably not needed by Jamulus anyway.
Someone should try removing that line and building + running Jamulus.

If the program runs fine without that line, commit the change and you're done.

**Comment by hoffie** [comment]
#174's most recent build no longer shows a dbus-related issue. It seems like @ranfdev's suggestion has been [implemented in that PR](https://github.com/flathub/io.jamulus.Jamulus/pull/174/files#diff-2360eea7e96c042bbb43f5e20970d8b588eafe4cb3b5a297aaf71c2e8129b39bL13).

```
Error: icon io.jamulus.jamulus not found below /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-1B1YCd/files/share/icons
```

**Comment by 38github** [comment]
Any update?

**Comment by ann0see** [comment]
No. Sorry. I've given up as it got very confusing -

**Comment by 38github** [comment]
> No. Sorry. I've given up as it got very confusing -

Thank you for looking at it and tried your best.

**Comment by ann0see** [comment]
I thought it would be an easy fix as just the file name needs to be changed. 
I think someone who knows flatpak more could fix it in a few minutes - but it seems we don't have anyone 😒.
