### ISSUE TITLE
Outdated. Latest version is 3.9.1

### ISSUE THREAD

**Issue by 38github** [flathub/io.jamulus.Jamulus#289]
Outdated. Latest version is 3.9.1

**Comment by ann0see** [comment]
@joao-p-marques I've now deleted all branches which got created by the bot in the time the build failed (otherwise the repo would be very messy). I hope that's ok.

**Comment by joao-p-marques** [comment]
> @joao-p-marques I've now deleted all branches which got created by the bot in the time the build failed (otherwise the repo would be very messy). I hope that's ok.

Awesome, thank you very much @ann0see
